/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Mark_-_1_Elbow_Exoskeleton_-GLB1.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_0_1: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_1_1: THREE.Mesh
    mesh_1_2: THREE.Mesh
    ['Exo_Arm_Mark_1_-_Moving_Link-1']: THREE.Mesh
    ['Hinge-2']: THREE.Mesh
    ['Hinge-6']: THREE.Mesh
    ['Hinge-5']: THREE.Mesh
    ['Hinge-3']: THREE.Mesh
    ['Hinge-7']: THREE.Mesh
    ['Hinge-9']: THREE.Mesh
    ['Hinge-4']: THREE.Mesh
    ['Hinge-8']: THREE.Mesh
    ['M3_Allen_Bolt-1']: THREE.Mesh
    ['M6_Bolt-8']: THREE.Mesh
    ['M6_Bolt-12']: THREE.Mesh
    ['M6_Bolt-15']: THREE.Mesh
    ['M6_Bolt-13']: THREE.Mesh
    ['M6_Bolt-14']: THREE.Mesh
    ['M6_Bolt-17']: THREE.Mesh
    ['M6_Bolt-16']: THREE.Mesh
    ['M6_Bolt-18']: THREE.Mesh
    ['M6_Bolt-9']: THREE.Mesh
    mesh_21: THREE.Mesh
    mesh_21_1: THREE.Mesh
    mesh_21_2: THREE.Mesh
    mesh_21_3: THREE.Mesh
    mesh_22: THREE.Mesh
    mesh_22_1: THREE.Mesh
    mesh_22_2: THREE.Mesh
    mesh_22_3: THREE.Mesh
    ['M6_Bolt-2']: THREE.Mesh
    ['M6_Bolt-1']: THREE.Mesh
    ['M6_Bolt-4']: THREE.Mesh
    ['M6_Bolt-3']: THREE.Mesh
    ['M6_Bolt-5']: THREE.Mesh
    ['M6_Bolt-6']: THREE.Mesh
    ['M6_Bolt-7']: THREE.Mesh
    ['M6_Bolt-11']: THREE.Mesh
    ['M6_Bolt-10']: THREE.Mesh
    ['M6_Bolt-22']: THREE.Mesh
    ['M6_Bolt-21']: THREE.Mesh
    ['M6_Bolt-20']: THREE.Mesh
    ['M6_Bolt-19']: THREE.Mesh
    ['M3_Bolt-1']: THREE.Mesh
    ['M3_Allen_Bolt-2']: THREE.Mesh
    ['M3_Bolt-6']: THREE.Mesh
    ['M3_Bolt-3']: THREE.Mesh
    ['M3_Bolt-2']: THREE.Mesh
    ['M3_Bolt-5']: THREE.Mesh
    ['M3_Bolt-4']: THREE.Mesh
    ['M3_Allen_Bolt-3']: THREE.Mesh
  }
  materials: {
    defaultplastic: THREE.MeshStandardMaterial
    defaultplastic: THREE.MeshStandardMaterial
    defaultplastic: THREE.MeshStandardMaterial
    defaultplastic: THREE.MeshStandardMaterial
    defaultplastic: THREE.MeshStandardMaterial
    defaultplastic: THREE.MeshStandardMaterial
    defaultplastic: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Mark_-_1_Elbow_Exoskeleton_-GLB1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera makeDefault={false} far={3.133} near={1.828} position={[0.318, 0.622, -0.843]} rotation={[3.026, -0.217, 2.493]} />
      <group position={[0.684, 0.832, 1.327]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials.defaultplastic} />
      </group>
      <group position={[0.684, 0.832, 1.326]}>
        <mesh geometry={nodes.mesh_1.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_1_1.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_1_2.geometry} material={materials.defaultplastic} />
      </group>
      <mesh geometry={nodes['Exo_Arm_Mark_1_-_Moving_Link-1'].geometry} material={materials.defaultplastic} position={[0.683, 0.832, 1.328]} rotation={[0, 0, 2.103]} />
      <mesh geometry={nodes['Hinge-2'].geometry} material={materials.defaultplastic} position={[0.72, 0.875, 1.329]} rotation={[-Math.PI / 2, 1.038, 0.414]} />
      <mesh geometry={nodes['Hinge-6'].geometry} material={materials.defaultplastic} position={[0.612, 0.814, 1.321]} rotation={[-2.004, -1.571, 0]} />
      <mesh geometry={nodes['Hinge-5'].geometry} material={materials.defaultplastic} position={[0.812, 0.886, 1.329]} rotation={[Math.PI / 2, -1.038, -2.728]} />
      <mesh geometry={nodes['Hinge-3'].geometry} material={materials.defaultplastic} position={[0.765, 0.902, 1.329]} rotation={[-Math.PI / 2, 1.038, 0.414]} />
      <mesh geometry={nodes['Hinge-7'].geometry} material={materials.defaultplastic} position={[0.567, 0.814, 1.321]} rotation={[-2.004, -1.571, 0]} />
      <mesh geometry={nodes['Hinge-9'].geometry} material={materials.defaultplastic} position={[0.534, 0.851, 1.321]} rotation={[-1.137, 1.571, 0]} />
      <mesh geometry={nodes['Hinge-4'].geometry} material={materials.defaultplastic} position={[0.767, 0.86, 1.329]} rotation={[Math.PI / 2, -1.038, -2.728]} />
      <mesh geometry={nodes['Hinge-8'].geometry} material={materials.defaultplastic} position={[0.579, 0.851, 1.321]} rotation={[-1.137, 1.571, 0]} />
      <mesh geometry={nodes['M3_Allen_Bolt-1'].geometry} material={materials.defaultplastic} position={[0.696, 0.826, 1.339]} rotation={[-Math.PI, 0, -1.629]} />
      <mesh geometry={nodes['M6_Bolt-8'].geometry} material={materials.defaultplastic} position={[0.771, 0.923, 1.341]} rotation={[-2.287, -0.418, 2.97]} />
      <mesh geometry={nodes['M6_Bolt-12'].geometry} material={materials.defaultplastic} position={[0.618, 0.832, 1.321]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['M6_Bolt-15'].geometry} material={materials.defaultplastic} position={[0.573, 0.832, 1.321]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['M6_Bolt-13'].geometry} material={materials.defaultplastic} position={[0.603, 0.832, 1.321]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['M6_Bolt-14'].geometry} material={materials.defaultplastic} position={[0.588, 0.832, 1.321]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['M6_Bolt-17'].geometry} material={materials.defaultplastic} position={[0.543, 0.832, 1.321]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['M6_Bolt-16'].geometry} material={materials.defaultplastic} position={[0.558, 0.832, 1.321]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['M6_Bolt-18'].geometry} material={materials.defaultplastic} position={[0.528, 0.832, 1.321]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['M6_Bolt-9'].geometry} material={materials.defaultplastic} position={[0.726, 0.896, 1.341]} rotation={[-2.287, -0.418, -0.507]} />
      <group position={[0.472, 0.832, 1.374]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.mesh_21.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_21_1.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_21_2.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_21_3.geometry} material={materials.defaultplastic} />
      </group>
      <group position={[0.846, 0.928, 1.381]} rotation={[Math.PI / 2, -1.038, -Math.PI]}>
        <mesh geometry={nodes.mesh_22.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_22_1.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_22_2.geometry} material={materials.defaultplastic} />
        <mesh geometry={nodes.mesh_22_3.geometry} material={materials.defaultplastic} />
      </group>
      <mesh geometry={nodes['M6_Bolt-2'].geometry} material={materials.defaultplastic} position={[0.772, 0.884, 1.33]} rotation={[Math.PI, 0, 2.609]} />
      <mesh geometry={nodes['M6_Bolt-1'].geometry} material={materials.defaultplastic} position={[0.798, 0.9, 1.33]} rotation={[Math.PI, 0, 2.609]} />
      <mesh geometry={nodes['M6_Bolt-4'].geometry} material={materials.defaultplastic} position={[0.746, 0.869, 1.33]} rotation={[Math.PI, 0, 2.609]} />
      <mesh geometry={nodes['M6_Bolt-3'].geometry} material={materials.defaultplastic} position={[0.759, 0.877, 1.33]} rotation={[Math.PI, 0, 2.609]} />
      <mesh geometry={nodes['M6_Bolt-5'].geometry} material={materials.defaultplastic} position={[0.733, 0.861, 1.33]} rotation={[Math.PI, 0, 2.609]} />
      <mesh geometry={nodes['M6_Bolt-6'].geometry} material={materials.defaultplastic} position={[0.785, 0.892, 1.33]} rotation={[Math.PI, 0, 2.609]} />
      <mesh geometry={nodes['M6_Bolt-7'].geometry} material={materials.defaultplastic} position={[0.721, 0.854, 1.33]} rotation={[Math.PI, 0, 2.609]} />
      <mesh geometry={nodes['M6_Bolt-11'].geometry} material={materials.defaultplastic} position={[0.806, 0.865, 1.341]} rotation={[2.287, 0.418, 2.634]} />
      <mesh geometry={nodes['M6_Bolt-10'].geometry} material={materials.defaultplastic} position={[0.76, 0.838, 1.341]} rotation={[2.287, 0.418, -0.172]} />
      <mesh geometry={nodes['M6_Bolt-22'].geometry} material={materials.defaultplastic} position={[0.55, 0.799, 1.333]} rotation={[2.194, 0, -0.292]} />
      <mesh geometry={nodes['M6_Bolt-21'].geometry} material={materials.defaultplastic} position={[0.596, 0.799, 1.333]} rotation={[2.194, 0, -2.849]} />
      <mesh geometry={nodes['M6_Bolt-20'].geometry} material={materials.defaultplastic} position={[0.55, 0.866, 1.333]} rotation={[-2.194, 0, 0.292]} />
      <mesh geometry={nodes['M6_Bolt-19'].geometry} material={materials.defaultplastic} position={[0.596, 0.866, 1.333]} rotation={[-2.194, 0, 2.849]} />
      <mesh geometry={nodes['M3_Bolt-1'].geometry} material={materials.defaultplastic} position={[0.684, 0.807, 1.329]} rotation={[Math.PI, 0, 2.616]} />
      <mesh geometry={nodes['M3_Allen_Bolt-2'].geometry} material={materials.defaultplastic} position={[0.672, 0.825, 1.339]} rotation={[Math.PI, 0, 0.466]} />
      <mesh geometry={nodes['M3_Bolt-6'].geometry} material={materials.defaultplastic} position={[0.662, 0.82, 1.329]} rotation={[-Math.PI, 0, -2.62]} />
      <mesh geometry={nodes['M3_Bolt-3'].geometry} material={materials.defaultplastic} position={[0.706, 0.845, 1.329]} rotation={[Math.PI, 0, 0.521]} />
      <mesh geometry={nodes['M3_Bolt-2'].geometry} material={materials.defaultplastic} position={[0.706, 0.82, 1.329]} rotation={[Math.PI, 0, 1.569]} />
      <mesh geometry={nodes['M3_Bolt-5'].geometry} material={materials.defaultplastic} position={[0.662, 0.845, 1.329]} rotation={[-Math.PI, 0, -1.573]} />
      <mesh geometry={nodes['M3_Bolt-4'].geometry} material={materials.defaultplastic} position={[0.684, 0.857, 1.329]} rotation={[-Math.PI, 0, -0.526]} />
      <mesh geometry={nodes['M3_Allen_Bolt-3'].geometry} material={materials.defaultplastic} position={[0.684, 0.846, 1.339]} rotation={[Math.PI, 0, 2.56]} />
    </group>
  )
}

useGLTF.preload('/Mark_-_1_Elbow_Exoskeleton_-GLB1.glb')
