const $=id=>document.getElementById(id);let globe,records,geo,layer='stroke',selected,rotating=false;
const compact=n=>n>=1e9?(n/1e9).toFixed(2)+'B':n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(n);
const metrics={stroke:'people living with stroke',incident:'new stroke cases during the year',rehab:'people who may benefit from rehabilitation'};
const primary=['India','China','Japan','Australia','United States of America','Brazil','United Kingdom','Russia','South Africa','Nigeria','Indonesia','Canada'];
function getYear(d){return layer==='rehab'?d.rehabYear:'2021'}
function source(d){return layer==='rehab'?d.rehabSource:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12254192/'}
function setRotation(on){rotating=on;if(globe)globe.controls().autoRotate=on;$('rotate').setAttribute('aria-pressed',on);$('rotate').textContent=on?'Ⅱ':'▷'}
function showCountry(d,fly=true){selected=d;$('country').value=d.code;$('countryName').textContent=d.name;const val=d[layer];$('countryValue').textContent=val==null?'Not available':(layer==='rehab'&&d.name==='India'?'> ':'')+compact(val);$('countryValue').style.fontSize=val==null?'25px':'';$('countryMetric').textContent=metrics[layer];$('countryYear').textContent=val==null?'—':getYear(d);$('countryDetail').textContent=val==null?'No estimate is included for this country in this layer. This does not mean zero need.':layer==='rehab'?d.rehabNote:'95% uncertainty interval: '+(layer==='stroke'?d.ui:d.incidentUI)+'. All ages, both sexes.';$('countrySource').hidden=val==null;$('countrySource').href=source(d)||'#';if(globe){updateLayers();if(fly){setRotation(false);globe.pointOfView({lat:d.lat,lng:d.lng,altitude:2.1},1100)}}}
function updateLayers(){const available=records.filter(d=>d[layer]!=null);$('coverage').textContent=available.length+' countries with data';const labels=available.filter(d=>primary.includes(d.name)||d===selected||layer==='rehab');globe.htmlElementsData(labels).pointsData(available).polygonCapColor(f=>f.properties.code===selected.code?'rgba(77,216,195,0.16)':'rgba(0,0,0,0)').polygonStrokeColor(f=>f.properties.code===selected.code?'#77e6d1':'rgba(135,197,205,0.19)');}
function changeLayer(next){layer=next;document.querySelectorAll('[data-layer]').forEach(b=>{const active=b.dataset.layer===layer;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});$('globalValue').innerHTML=layer==='stroke'?'93.8<span>M</span>':layer==='incident'?'11.9<span>M</span>':'2.41<span>B</span>';$('globalLabel').textContent=layer==='rehab'?'people worldwide could benefit from rehabilitation':metrics[layer]+' worldwide';$('globalYear').textContent=layer==='rehab'?'WHO / GBD 2019 · Global estimate':'GBD 2021 · All ages · Both sexes';$('layerNote').textContent=layer==='rehab'?'Selected-country coverage · Different reporting years. Rehabilitation includes more than physiotherapy.':layer==='stroke'?'Modelled prevalence, not a count of people receiving treatment.':'Modelled annual incidence, not the total number of survivors.';showCountry(selected,false)}
async function init(){try{[records,geo]=await Promise.all([fetch('./assets/data.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('./assets/countries.json').then(r=>{if(!r.ok)throw Error();return r.json()})]);records.sort((a,b)=>a.name.localeCompare(b.name));records.forEach(d=>{const o=document.createElement('option');o.value=d.code;o.textContent=d.name;$('country').append(o)});selected=records.find(d=>d.name==='India');$('country').onchange=e=>showCountry(records.find(d=>d.code===e.target.value));document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>changeLayer(b.dataset.layer));showCountry(selected,false);
try{globe=new Globe($('globe'),{animateIn:!matchMedia('(prefers-reduced-motion: reduce)').matches}).backgroundColor('#060d12').globeImageUrl('./assets/earth.jpg').bumpImageUrl('./assets/bump.png').showAtmosphere(true).atmosphereColor('#51a6b5').atmosphereAltitude(.14).polygonsData(geo.features.filter(f=>f.properties.name!=='Antarctica')).polygonAltitude(.002).polygonSideColor(()=> 'rgba(0,0,0,0)').polygonLabel(f=>f.properties.name).onPolygonClick(f=>{const d=records.find(d=>d.code===f.properties.code);if(d)showCountry(d)}).pointLat('lat').pointLng('lng').pointAltitude(.008).pointRadius(d=>d===selected?.22:.085).pointColor(()=> '#70ecd3').pointLabel(d=>d.name+': '+compact(d[layer])).onPointClick(d=>showCountry(d)).htmlLat('lat').htmlLng('lng').htmlAltitude(.025).htmlElement(d=>{const el=document.createElement('button');el.className='globe-label'+(d===selected?' selected':'');el.type='button';el.setAttribute('aria-label',d.name+', '+compact(d[layer])+' '+metrics[layer]);el.append(document.createTextNode(d.name==='United States of America'?'United States':d.name));const b=document.createElement('b');b.textContent=(layer==='rehab'&&d.name==='India'?'>':'')+compact(d[layer]);el.append(b);el.onclick=()=>showCountry(d);return el});globe.controls().enablePan=false;globe.controls().enableZoom=false;globe.controls().enableRotate=!matchMedia('(max-width:700px)').matches;const canvas=globe.renderer().domElement;canvas.style.touchAction='pan-y';globe.controls().minDistance=155;globe.controls().maxDistance=500;globe.controls().autoRotateSpeed=.28;globe.controls().addEventListener('start',()=>setRotation(false));globe.pointOfView({lat:21,lng:76,altitude:2.15});globe.renderer().setPixelRatio(Math.min(window.devicePixelRatio,2));new ResizeObserver(()=>globe.width($('globe').clientWidth).height($('globe').clientHeight)).observe($('globe'));updateLayers();new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting?globe.resumeAnimation():globe.pauseAnimation()),{rootMargin:'100px'}).observe($('globe'));$('loading').hidden=true;}catch(e){$('loading').textContent='3D view unavailable. Explore the country data using the selector below.';document.querySelector('.world-controls').hidden=true;console.error(e)}
}catch(e){$('loading').textContent='Could not load the atlas. Please refresh to try again.';console.error(e)}}
$('rotate').onclick=()=>setRotation(!rotating);$('zoomIn').onclick=()=>{if(globe){const p=globe.pointOfView();globe.pointOfView({...p,altitude:Math.max(.6,p.altitude-.35)},400)}};$('zoomOut').onclick=()=>{if(globe){const p=globe.pointOfView();globe.pointOfView({...p,altitude:Math.min(4,p.altitude+.35)},400)}};$('reset').onclick=()=>showCountry(records.find(d=>d.name==='India'));$('sources').onclick=$('method').onclick=()=>$('dataDialog').showModal();$('closeDialog').onclick=()=>$('dataDialog').close();$('dataDialog').onclick=e=>{if(e.target===$('dataDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};init();
